
default:
  remote:
    host: translate-sandbox.geni.com
    access_token: 
    app_key:
    testing: default 

  current_locale: en-US
  disabled: false

dev:
  remote:
    host: translate-sandbox.geni.com
	testing: dev
