
default:
  remote:
    host: translate-sandbox.geni.com
    client_id: 49695651ced49a2bc
    access_token: 
    app_key:

  current_locale: en-US
  disabled: false

dev:
  remote:
    host: 192.168.52.73
    client_id: 30788a6518275b178
    access_token: 61adfb452edc4cc85
